#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import datetime

import os

pwd = os.path.abspath('.')
print('\tSize\tLast Modified\tName')
print('----------------------------------')

for f in os.listdir(pwd):
    size = os.path.getsize(f)
    mtime = str(datetime.fromtimestamp(os.path.getmtime(f))).split('.')[0]
    flag = '/' if os.path.isdir(f) else ''
    print('%10d\t%s\t\t%s%s' %(size,mtime,f,flag))
